---
version: 2

workflows:
  version: 2
  program-analysis:
    jobs:
      - asan
      - tsan
      - alpine-normal

jobs:
  asan:
    working_directory: ~/work
    docker:
      - image: ubuntu:bionic

    steps:
      - run: &apt_install
          apt-get update &&
          DEBIAN_FRONTEND=noninteractive
          apt-get install -y --no-install-recommends
            ca-certificates
            clang
            cmake
            git
            libconfig-dev
            libgtest-dev
            libopus-dev
            libsodium-dev
            libvpx-dev
            llvm-dev
            ninja-build
            pkg-config
            libavutil-dev
            libavcodec-dev
            libavformat-dev
            libavfilter-dev
            libx264-dev
      - checkout
      - run: git submodule update --init --recursive
      - run: CC=clang .circleci/cmake-asan

  tsan:
    working_directory: ~/work
    docker:
      - image: ubuntu:bionic

    steps:
      - run: *apt_install
      - checkout
      - run: git submodule update --init --recursive
      - run: CC=clang .circleci/cmake-tsan

  alpine-normal:
    docker:
      - image: alpine

    steps:
      - checkout
      - run: id;pwd;echo $0
      - run: |
          apk update && \
          apk add bash
      - run: |
          apk add \
          wget \
          git \
          cmake \
          automake \
          autoconf \
          check \
          libtool \
          rsync \
          nano \
          gcc \
          g++ \
          clang \
          clang-extra-tools \
          clang-analyzer \
          libconfig-dev \
          libsodium-dev \
          opus-dev \
          libvpx-dev \
          x264-dev \
          ffmpeg4-dev \
          ninja \
          pkgconf-dev \
          make \
          yasm \
          file \
          linux-headers \
          binutils \
          gtest-dev \
          llvm-dev
      - run: |
          rm -f /usr/bin/c++;
          rm -f /usr/bin/g++;
          cd /usr/bin/;
          ln -f /usr/bin/clang++ c++;
          ln -f /usr/bin/clang++ g++
      - run: git submodule update --init --recursive
      - run: CC=clang .circleci/cmake-normal

